### ISSUE TITLE
Does .rem account for evolved Featured?

### ISSUE THREAD

**Issue by Raijinili** [necromanteion/python-sakubot#1]
Some Godfests include the evolved versions of featured pantheons. Is there a syntax to specify that?

**Comment by wmedlar** [comment]
Yep, they're included whenever a fest is specified, currently at the default 6\* rate.

Here's an example from the [Greco lineup](https://github.com/necromanteion/python-sakubot/blob/master/sakubot/plugins/rem/events.py#L130]).
